# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20dadf44daf1279df17aa4536b5a0e4826829c589cb3b52de4f82a566a5bcf901f411a38a59df88526b88ac7145fdf6c0177ad6ed2af25bba434bedae472e0b5

test:
  secret_key_base: 267ebd0586ebee30037a74132055ff33e601d66c3f479cffb5494cef7e312c09bc688e754b38a72e7a13347b0b5d0e80f35d54c907684bcfd229c36121ce1fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
